global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "fastapi_serving_pipeline"
    static_configs:
      # FastAPI is running directly on the host (not in Docker)
      # with uvicorn on port 8000
      - targets: ["localhost:8000"]

